"""empty message

Revision ID: 56593d8a6bb4
Revises: d648c878c260
Create Date: 2021-09-14 11:33:59.165800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56593d8a6bb4'
down_revision = 'd648c878c260'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_files',
    sa.Column('videoID', sa.Integer(), nullable=False),
    sa.Column('videoName', sa.String(length=300), nullable=False),
    sa.Column('videoData', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('videoID')
    )
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['therapyid'], ['id'])

    # ### end Alembic commands ###


