"""empty message

Revision ID: 37be35d952e2
Revises: d660122cd4fa
Create Date: 2021-09-14 10:38:56.670016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37be35d952e2'
down_revision = 'd660122cd4fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('therapyid', sa.Integer(), nullable=False))
    op.drop_constraint(None, 'patient', type_='foreignkey')
    op.create_foreign_key(None, 'patient', 'user', ['therapyid'], ['id'])
    op.drop_column('patient', 'therapy_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('therapy_id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'patient', type_='foreignkey')
    op.create_foreign_key(None, 'patient', 'user', ['therapy_id'], ['id'])
    op.drop_column('patient', 'therapyid')
    # ### end Alembic commands ###
