"""empty message

Revision ID: 8757c80982c8
Revises: be95464f81bd
Create Date: 2021-08-29 15:48:07.178158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8757c80982c8'
down_revision = 'be95464f81bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('title', sa.String(length=5), nullable=True))
    op.add_column('patient', sa.Column('firstname', sa.String(length=120), nullable=True))
    op.add_column('patient', sa.Column('lastname', sa.String(length=120), nullable=True))
    op.add_column('patient', sa.Column('city', sa.String(length=120), nullable=True))
    op.add_column('patient', sa.Column('country', sa.String(length=60), nullable=True))
    op.add_column('patient', sa.Column('dob', sa.DateTime(), nullable=True))
    op.add_column('patient', sa.Column('guardiantitle', sa.String(length=5), nullable=True))
    op.add_column('patient', sa.Column('guardianfirstname', sa.String(length=120), nullable=True))
    op.add_column('patient', sa.Column('guardianlastname', sa.String(length=120), nullable=True))
    op.add_column('patient', sa.Column('relationship', sa.String(length=20), nullable=True))
    op.add_column('patient', sa.Column('email', sa.String(length=120), nullable=True))
    op.add_column('patient', sa.Column('countrycode', sa.String(length=5), nullable=True))
    op.add_column('patient', sa.Column('phonenumber', sa.Integer(), nullable=True))
    op.drop_column('patient', 'location')
    op.drop_column('patient', 'fullname')
    op.add_column('user', sa.Column('title', sa.String(length=10), nullable=True))
    op.add_column('user', sa.Column('organization', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'organization')
    op.drop_column('user', 'title')
    op.add_column('patient', sa.Column('fullname', sa.VARCHAR(length=120), nullable=True))
    op.add_column('patient', sa.Column('location', sa.VARCHAR(length=120), nullable=True))
    op.drop_column('patient', 'phonenumber')
    op.drop_column('patient', 'countrycode')
    op.drop_column('patient', 'email')
    op.drop_column('patient', 'relationship')
    op.drop_column('patient', 'guardianlastname')
    op.drop_column('patient', 'guardianfirstname')
    op.drop_column('patient', 'guardiantitle')
    op.drop_column('patient', 'dob')
    op.drop_column('patient', 'country')
    op.drop_column('patient', 'city')
    op.drop_column('patient', 'lastname')
    op.drop_column('patient', 'firstname')
    op.drop_column('patient', 'title')
    # ### end Alembic commands ###
